# Generated by Django 5.2.1 on 2025-05-19 07:48

import company.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_type', models.CharField(choices=[('added', 'Added'), ('removed', 'Removed'), ('updated', 'Updated')], max_length=10)),
                ('object_type', models.CharField(choices=[('Company', 'Company'), ('Director', 'Director'), ('Shareholder', 'Shareholder'), ('TaxInfo', 'TaxInfo'), ('IdentityFile', 'IdentityFile')], max_length=20)),
                ('object_pid', models.CharField(max_length=16)),
                ('changes', models.JSONField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.CharField(default=company.models.generate_pid, editable=False, max_length=16, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('date_of_incorporation', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='IdentityFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.CharField(default=company.models.generate_pid, editable=False, max_length=16, unique=True)),
                ('file_name', models.CharField(max_length=255)),
                ('file_path', models.CharField(max_length=255)),
                ('file_type', models.CharField(max_length=50)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.CharField(default=company.models.generate_pid, editable=False, max_length=16, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='directors', to='company.company')),
                ('identity_files', models.ManyToManyField(blank=True, related_name='director_files', to='company.identityfile')),
            ],
        ),
        migrations.CreateModel(
            name='Shareholder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.CharField(default=company.models.generate_pid, editable=False, max_length=16, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shareholders', to='company.company')),
                ('identity_files', models.ManyToManyField(blank=True, related_name='shareholder_files', to='company.identityfile')),
            ],
        ),
        migrations.CreateModel(
            name='TaxInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.CharField(default=company.models.generate_pid, editable=False, max_length=16, unique=True)),
                ('tin', models.CharField(max_length=50, verbose_name='Tax Identification Number')),
                ('country', models.CharField(max_length=2)),
                ('object_id', models.CharField(max_length=16)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
    ]
