# Generated by Django 5.2.1 on 2025-05-19 08:03

import company.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changelog',
            name='changes',
            field=models.JSONField(blank=True, encoder=company.models.DateJSONEncoder, null=True),
        ),
    ]
